import crypto from 'node:crypto';
import express from 'express';
import cors from 'cors';
import 'dotenv/config';

const app=express();
const WEB_URL=process.env.WEB_ORIGIN||'https://habeshaimexai-cyber.github.io/creatoros-ai/';
const WEB_ORIGIN=new URL(WEB_URL).origin;
app.use(cors({origin:(o,cb)=>cb(null,!o||o===WEB_ORIGIN),methods:['GET','POST']}));
app.use(express.json({limit:'100kb'}));

const core=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','TOKEN_ENCRYPTION_KEY'];
const configured=keys=>[...core,...keys].every(k=>Boolean(process.env[k]));
const key=()=>crypto.createHash('sha256').update(process.env.TOKEN_ENCRYPTION_KEY||'missing').digest();
function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return[iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),data.toString('base64url')].join('.')}
function state(userId){return seal(JSON.stringify({userId,exp:Date.now()+600000}))}
function readState(value){const[i,t,d]=String(value).split('.'),decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64url'));decipher.setAuthTag(Buffer.from(t,'base64url'));const p=JSON.parse(Buffer.concat([decipher.update(Buffer.from(d,'base64url')),decipher.final()]).toString());if(!p.userId||p.exp<Date.now())throw Error('Anmeldung ist abgelaufen.');return p}
async function user(auth){if(!auth?.startsWith('Bearer ')||!configured([]))return null;const r=await fetch(process.env.SUPABASE_URL+'/auth/v1/user',{headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,authorization:auth}});return r.ok?r.json():null}
async function save(row){const r=await fetch(process.env.SUPABASE_URL+'/rest/v1/social_connections?on_conflict=user_id,platform,account_id',{method:'POST',headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'content-type':'application/json',prefer:'resolution=merge-duplicates'},body:JSON.stringify(row)});if(!r.ok)throw Error('Konto konnte nicht gespeichert werden.')}
const tokenFields=t=>({access_token:seal(t.access_token),refresh_token:t.refresh_token?seal(t.refresh_token):null,expires_at:t.expires_in?new Date(Date.now()+Number(t.expires_in)*1000).toISOString():null,scopes:String(t.scope||'').split(/[ ,]+/).filter(Boolean),status:'ACTIVE'});
function finish(res,message,success=false){const data=JSON.stringify({type:'creatoros-oauth',success,message});res.type('html').send(`<!doctype html><meta name="viewport" content="width=device-width"><title>CreatorOS</title><body style="margin:0;background:#09090b;color:#fafafa;font-family:system-ui"><main style="max-width:520px;margin:80px auto;padding:28px"><h1>${success?'✓ Konto verbunden':'Verbindung fehlgeschlagen'}</h1><p>${message}</p><p>Dieses Fenster schließt sich automatisch.</p></main><script>if(opener)opener.postMessage(${data},${JSON.stringify(WEB_ORIGIN)});setTimeout(()=>close(),1800)<\/script></body>`)}

app.get('/health',(_q,res)=>res.json({status:'ok',service:'CreatorOS API',version:'2026-09-social-ai',platforms:{youtube:configured(['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REDIRECT_URI']),meta:configured(['META_APP_ID','META_APP_SECRET','META_REDIRECT_URI']),tiktok:configured(['TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET','TIKTOK_REDIRECT_URI'])},ai:{openai:Boolean(process.env.OPENAI_API_KEY),gemini:Boolean(process.env.GEMINI_API_KEY),claude:Boolean(process.env.ANTHROPIC_API_KEY)}}));
app.get('/connections',async(req,res)=>{const u=await user(req.get('authorization'));if(!u?.id)return res.status(401).json({error:'Bitte zuerst anmelden.'});const r=await fetch(process.env.SUPABASE_URL+`/rest/v1/social_connections?select=platform,account_id,handle,status&user_id=eq.${encodeURIComponent(u.id)}`,{headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY}});res.status(r.ok?200:502).json(r.ok?{connections:await r.json()}:{error:'Konten konnten nicht geladen werden.'})});

app.post('/oauth/youtube/start',async(req,res)=>{if(!configured(['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REDIRECT_URI']))return res.status(503).json({error:'YouTube ist noch nicht konfiguriert.'});const u=await user(req.get('authorization'));if(!u?.id)return res.status(401).json({error:'Bitte zuerst anmelden.'});const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:process.env.GOOGLE_REDIRECT_URI,response_type:'code',access_type:'offline',prompt:'consent',state:state(u.id),scope:'https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/yt-analytics.readonly'});res.json({url:'https://accounts.google.com/o/oauth2/v2/auth?'+p})});
app.get('/oauth/youtube/callback',async(req,res)=>{try{const{userId}=readState(req.query.state),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:String(req.query.code),client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})}),t=await r.json();if(!r.ok||!t.access_token)throw Error('Google-Berechtigung wurde nicht akzeptiert.');const cr=await fetch('https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true',{headers:{authorization:'Bearer '+t.access_token}}),channel=(await cr.json()).items?.[0];if(!channel?.id)throw Error('Kein YouTube-Kanal gefunden.');await save({user_id:userId,platform:'YOUTUBE',account_id:channel.id,handle:channel.snippet?.customUrl||channel.snippet?.title||'YouTube',...tokenFields(t)});finish(res,'Dein YouTube-Kanal ist jetzt mit CreatorOS verbunden.',true)}catch(e){finish(res,e.message)}});

app.post('/oauth/facebook/start',async(req,res)=>{if(!configured(['META_APP_ID','META_APP_SECRET','META_REDIRECT_URI']))return res.status(503).json({error:'Facebook und Instagram sind noch nicht konfiguriert.'});const u=await user(req.get('authorization'));if(!u?.id)return res.status(401).json({error:'Bitte zuerst anmelden.'});const p=new URLSearchParams({client_id:process.env.META_APP_ID,redirect_uri:process.env.META_REDIRECT_URI,response_type:'code',state:state(u.id),scope:'public_profile,pages_show_list,pages_read_engagement,instagram_basic,instagram_manage_insights'});res.json({url:'https://www.facebook.com/v23.0/dialog/oauth?'+p})});
app.get('/oauth/facebook/callback',async(req,res)=>{try{const{userId}=readState(req.query.state),url=new URL('https://graph.facebook.com/v23.0/oauth/access_token');url.search=new URLSearchParams({client_id:process.env.META_APP_ID,client_secret:process.env.META_APP_SECRET,redirect_uri:process.env.META_REDIRECT_URI,code:String(req.query.code)});const tr=await fetch(url),t=await tr.json();if(!tr.ok||!t.access_token)throw Error('Meta-Berechtigung wurde nicht akzeptiert.');const ar=await fetch('https://graph.facebook.com/v23.0/me/accounts?fields=id,name,access_token,instagram_business_account{id,username}&access_token='+encodeURIComponent(t.access_token)),accounts=(await ar.json()).data||[];if(!accounts.length)throw Error('Keine Facebook-Seite gefunden. Verbinde zuerst eine Facebook-Seite.');for(const page of accounts){await save({user_id:userId,platform:'FACEBOOK',account_id:page.id,handle:page.name||'Facebook',...tokenFields({...t,access_token:page.access_token||t.access_token})});if(page.instagram_business_account?.id)await save({user_id:userId,platform:'INSTAGRAM',account_id:page.instagram_business_account.id,handle:page.instagram_business_account.username||'Instagram',...tokenFields(t)})}finish(res,'Facebook'+(accounts.some(x=>x.instagram_business_account)?' und Instagram wurden':' wurde')+' verbunden.',true)}catch(e){finish(res,e.message)}});

app.post('/oauth/tiktok/start',async(req,res)=>{if(!configured(['TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET','TIKTOK_REDIRECT_URI']))return res.status(503).json({error:'TikTok ist vorbereitet. Es fehlen noch die TikTok-Entwicklerdaten.'});const u=await user(req.get('authorization'));if(!u?.id)return res.status(401).json({error:'Bitte zuerst anmelden.'});const p=new URLSearchParams({client_key:process.env.TIKTOK_CLIENT_KEY,response_type:'code',scope:'user.info.basic,video.list',redirect_uri:process.env.TIKTOK_REDIRECT_URI,state:state(u.id)});res.json({url:'https://www.tiktok.com/v2/auth/authorize/?'+p})});
app.get('/oauth/tiktok/callback',async(req,res)=>{try{const{userId}=readState(req.query.state),r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:process.env.TIKTOK_CLIENT_KEY,client_secret:process.env.TIKTOK_CLIENT_SECRET,code:String(req.query.code),grant_type:'authorization_code',redirect_uri:process.env.TIKTOK_REDIRECT_URI})}),t=await r.json();if(!r.ok||!t.access_token)throw Error('TikTok-Berechtigung wurde nicht akzeptiert.');const pr=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,username',{headers:{authorization:'Bearer '+t.access_token}}),profile=(await pr.json()).data?.user;if(!profile?.open_id)throw Error('TikTok-Profil konnte nicht gelesen werden.');await save({user_id:userId,platform:'TIKTOK',account_id:profile.open_id,handle:profile.username||profile.display_name||'TikTok',...tokenFields(t)});finish(res,'Dein TikTok-Konto ist jetzt verbunden.',true)}catch(e){finish(res,e.message)}});

const system='Du bist ein erfahrener Social-Media-Stratege. Antworte nur als valides JSON mit title, hook, script, caption, hashtags (Array), bestTime, visualIdea und cta. Schreibe konkret, hilfreich und ohne erfundene aktuelle Fakten.';
function prompt(b){return `Sprache: ${b.language||'Deutsch'}\nPlattform: ${b.platform||'YouTube'}\nThema: ${String(b.topic||'').slice(0,300)}\nZiel: ${b.goal||'Reichweite'}\nStil: ${b.tone||'authentisch'}\nErstelle einen starken neuen Post.`}
async function aiGenerate(b){const p=prompt(b);if(process.env.OPENAI_API_KEY){const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{authorization:'Bearer '+process.env.OPENAI_API_KEY,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:p}]})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'GPT-Fehler');return{provider:'GPT',content:d.choices[0].message.content}}if(process.env.GEMINI_API_KEY){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${process.env.GEMINI_MODEL||'gemini-2.0-flash'}:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:system+'\n'+p}]}],generationConfig:{responseMimeType:'application/json'}})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Gemini-Fehler');return{provider:'Gemini',content:d.candidates[0].content.parts[0].text}}if(process.env.ANTHROPIC_API_KEY){const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model:process.env.ANTHROPIC_MODEL||'claude-3-5-haiku-latest',max_tokens:1200,system,messages:[{role:'user',content:p}]})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Claude-Fehler');return{provider:'Claude',content:d.content[0].text}}return null}
app.post('/ai/generate',async(req,res)=>{const u=await user(req.get('authorization'));if(!u?.id)return res.status(401).json({error:'Bitte zuerst anmelden.'});if(!String(req.body.topic||'').trim())return res.status(400).json({error:'Bitte gib ein Thema ein.'});try{const out=await aiGenerate(req.body);if(!out)return res.status(503).json({error:'KI ist vorbereitet. Auf dem Server muss noch ein GPT-, Gemini- oder Claude-Schlüssel eingetragen werden.'});res.json({provider:out.provider,result:JSON.parse(out.content.replace(/^```json\s*|\s*```$/g,''))})}catch(e){res.status(502).json({error:'KI-Antwort fehlgeschlagen: '+e.message})}});
app.listen(process.env.PORT||3001,()=>console.log('CreatorOS API läuft'));
