create table if not exists public.social_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('YOUTUBE', 'FACEBOOK', 'INSTAGRAM', 'TIKTOK')),
  account_id text not null,
  handle text not null,
  access_token text not null,
  refresh_token text,
  expires_at timestamptz,
  scopes text[] not null default '{}',
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, platform, account_id)
);

alter table public.social_connections enable row level security;

create policy "Users can read their own social connections"
  on public.social_connections for select to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.social_connections from anon, authenticated;
grant select (platform, account_id, handle, status) on public.social_connections to authenticated;
